### PR TITLE
⬆️ Update deposit tests

### PR DESCRIPTION
**Pull request by MattPoblete**
Add amounts = 0 test
Add overflow test
Add amount min > desired amount

### CODE REVIEW

**Comment by chopan123** [comment]
- [ ] Try to deposit more than you have
- [ ] Try to deposit an unsupported asset

**Comment by MattPoblete** [comment]
> * [ ]  Try to deposit an unsupported asset

Cant deposit "wrong asset" because we just send amounts, the vault manages directly the asset transfer
image

**Review by chopan123 — COMMENTED** [review]
parece que tambien el package.json

**Review by chopan123 — COMMENTED** [review]
parece que tambien el package.json

**Pull request merged**
