### PR TITLE
🩹 Fix blance reading submitting tx

### PR DESCRIPTION
**Pull request by MattPoblete**

### CODE REVIEW

**Comment by chopan123** [comment]
@MattPoblete test is failing:
```
root@fa2114fe901d:/workspace/apps/contracts# yarn test-two-strat-vault testnet
yarn run v1.22.21
$ tsc && node dist/tests/testTwoStrategiesVault.js testnet
src/tests/testTwoStrategiesVault.ts:13:65 - error TS2305: Module '"./vault.js"' has no exported member 'getVaultBalanceInStrategy'.

13 import { ActionType, AssetInvestmentAllocation, depositToVault, getVaultBalanceInStrategy, Instruction, investVault, rebalanceVault, fetchParsedCurrentIdleFunds, fetchCurrentInvestedFunds } from "./vault.js";
                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in src/tests/testTwoStrategiesVault.ts:13

error Command failed with exit code 2.
```

**Comment by chopan123** [comment]
eliminando el import tengo: 
```
simulation_resp {
  _parsed: true,
  id: undefined,
  latestLedger: 1265317,
  events: [
    ChildStruct { _attributes: [Object] },
    ChildStruct { _attributes: [Object] }
  ],
  error: 'HostError: Error(WasmVm, UnexpectedSize)\n' +
    '\n' +
    'Event log (newest first):\n' +
    '   0: [Diagnostic Event] contract:CCDWGZ4UJH3FIEBZPF3HPBVFYFYRCWKA3KNLBF4RXTCHASWX5UG6G44Q, topics:[error, Error(WasmVm, UnexpectedSize)], data:["VM call failed: Func(MismatchingParameterLen)", deposit]\n' +
    '   1: [Diagnostic Event] topics:[fn_call, CCDWGZ4UJH3FIEBZPF3HPBVFYFYRCWKA3KNLBF4RXTCHASWX5UG6G44Q, deposit], data:[[100000000000], [0], GAX4I6FRYPXI5IN6KRL7PC3UEUV6IGPULBOMIXLLYZDOHJEK75PEHAKF, false]\n'
}
❌ Deposit failed: Error: Simulation error
    at invokeTransaction (file:///workspace/apps/contracts/dist/utils/tx.js:27:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async invokeCustomContract (file:///workspace/apps/contracts/dist/utils/contract.js:70:12)
    at async depositToVault (file:///workspace/apps/contracts/dist/tests/vault.js:46:18)
    at async file:///workspace/apps/contracts/dist/tests/testTwoStrategiesVault.js:107:136
node:internal/modules/run_main:129
    triggerUncaughtException(
    ^

Error: Simulation error
    at invokeTransaction (file:///workspace/apps/contracts/dist/utils/tx.js:27:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async invokeCustomContract (file:///workspace/apps/contracts/dist/utils/contract.js:70:12)
    at async depositToVault (file:///workspace/apps/contracts/dist/tests/vault.js:46:18)
    at async file:///workspace/apps/contracts/dist/tests/testTwoStrategiesVault.js:107:136

Node.js v20.18.0
error Command failed with exit code 1.
```

**Comment by MattPoblete** [comment]
> eliminando el import tengo:
> 
> ```
> simulation_resp {
>   _parsed: true,
>   id: undefined,
>   latestLedger: 1265317,
>   events: [
>     ChildStruct { _attributes: [Object] },
>     ChildStruct { _attributes: [Object] }
>   ],
>   error: 'HostError: Error(WasmVm, UnexpectedSize)\n' +
>     '\n' +
>     'Event log (newest first):\n' +
>     '   0: [Diagnostic Event] contract:CCDWGZ4UJH3FIEBZPF3HPBVFYFYRCWKA3KNLBF4RXTCHASWX5UG6G44Q, topics:[error, Error(WasmVm, UnexpectedSize)], data:["VM call failed: Func(MismatchingParameterLen)", deposit]\n' +
>     '   1: [Diagnostic Event] topics:[fn_call, CCDWGZ4UJH3FIEBZPF3HPBVFYFYRCWKA3KNLBF4RXTCHASWX5UG6G44Q, deposit], data:[[100000000000], [0], GAX4I6FRYPXI5IN6KRL7PC3UEUV6IGPULBOMIXLLYZDOHJEK75PEHAKF, false]\n'
> }
> ❌ Deposit failed: Error: Simulation error
>     at invokeTransaction (file:///workspace/apps/contracts/dist/utils/tx.js:27:15)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async invokeCustomContract (file:///workspace/apps/contracts/dist/utils/contract.js:70:12)
>     at async depositToVault (file:///workspace/apps/contracts/dist/tests/vault.js:46:18)
>     at async file:///workspace/apps/contracts/dist/tests/testTwoStrategiesVault.js:107:136
> node:internal/modules/run_main:129
>     triggerUncaughtException(
>     ^
> 
> Error: Simulation error
>     at invokeTransaction (file:///workspace/apps/contracts/dist/utils/tx.js:27:15)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async invokeCustomContract (file:///workspace/apps/contracts/dist/utils/contract.js:70:12)
>     at async depositToVault (file:///workspace/apps/contracts/dist/tests/vault.js:46:18)
>     at async file:///workspace/apps/contracts/dist/tests/testTwoStrategiesVault.js:107:136
> 
> Node.js v20.18.0
> error Command failed with exit code 1.
> ```

El vault al que se estaba intentando depositar era un vault hardcodeado y desplegado por un factory antiguo, se refactorizó el test para desplegar un nuevo vault cada vez que se ejecute

**Comment by chopan123** [comment]
Me sigue tirando lo mismo :
```
simulation_resp {
  _parsed: true,
  id: undefined,
  latestLedger: 1267455,
  events: [
    ChildStruct { _attributes: [Object] },
    ChildStruct { _attributes: [Object] }
  ],
  error: 'HostError: Error(WasmVm, UnexpectedSize)\n' +
    '\n' +
    'Event log (newest first):\n' +
    '   0: [Diagnostic Event] contract:CBIPDDO5GYUOCP7HMAMSH66674AGTJCNBVPOUGILKAOKDL4HDOCOFXYD, topics:[error, Error(WasmVm, UnexpectedSize)], data:["VM call failed: Func(MismatchingParameterLen)", deposit]\n' +
    '   1: [Diagnostic Event] topics:[fn_call, CBIPDDO5GYUOCP7HMAMSH66674AGTJCNBVPOUGILKAOKDL4HDOCOFXYD, deposit], data:[[100000000000], [0], GC3JFCM3PSX7BHJ4RVYKYA7D4AH7GU52EL34B6BTR2POHOHISAXSDN7K, false]\n'
}
```

**Pull request merged**
